import pytest
import respx

from underflow.stackoverflow import StackOverflow


@pytest.fixture
def svf_answers_result():
    return {
        "items": [
            {
                "owner": {
                    "reputation": 3639,
                    "user_id": 2335020,
                    "user_type": "registered",
                    "accept_rate": 79,
                    "profile_image": "https://i.stack.imgur.com/ql0vj.png?s=128&g=1",
                    "display_name": "576i",
                    "link": "https://stackoverflow.com/users/2335020/576i",
                },
                "is_accepted": True,
                "score": 1,
                "last_activity_date": 1586554805,
                "last_edit_date": 1586554805,
                "creation_date": 1586541556,
                "answer_id": 61145970,
                "question_id": 61145838,
            },
            {
                "owner": {
                    "reputation": 56,
                    "user_id": 10847452,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/d38acea44beb79d417335af3609f15df?s=128&d=identicon&r=PG&f=1",
                    "display_name": "ivcuello",
                    "link": "https://stackoverflow.com/users/10847452/ivcuello",
                },
                "is_accepted": False,
                "score": 1,
                "last_activity_date": 1586547778,
                "creation_date": 1586547778,
                "answer_id": 61147570,
                "question_id": 42129181,
            },
            {
                "owner": {
                    "reputation": 71,
                    "user_id": 4971603,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/6f1bacd2ffa63c83700fa162b488c646?s=128&d=identicon&r=PG&f=1",
                    "display_name": "CristianoYL",
                    "link": "https://stackoverflow.com/users/4971603/cristianoyl",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1586547349,
                "creation_date": 1586547349,
                "answer_id": 61147453,
                "question_id": 58913803,
            },
            {
                "owner": {
                    "reputation": 1824,
                    "user_id": 6505847,
                    "user_type": "registered",
                    "profile_image": "https://i.stack.imgur.com/CmpDJ.jpg?s=128&g=1",
                    "display_name": "AzyCrw4282",
                    "link": "https://stackoverflow.com/users/6505847/azycrw4282",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1586547288,
                "last_edit_date": 1586547288,
                "creation_date": 1586493572,
                "answer_id": 61134137,
                "question_id": 61133669,
            },
            {
                "owner": {
                    "reputation": 73780,
                    "user_id": 354577,
                    "user_type": "registered",
                    "accept_rate": 100,
                    "profile_image": "https://www.gravatar.com/avatar/fd5da70153eaf04130797a71d78a01ef?s=128&d=identicon&r=PG",
                    "display_name": "Chris",
                    "link": "https://stackoverflow.com/users/354577/chris",
                },
                "is_accepted": True,
                "score": 0,
                "last_activity_date": 1586543809,
                "creation_date": 1586543809,
                "answer_id": 61146580,
                "question_id": 61146256,
            },
            {
                "owner": {
                    "reputation": 683,
                    "user_id": 2716435,
                    "user_type": "registered",
                    "accept_rate": 65,
                    "profile_image": "https://www.gravatar.com/avatar/779bb55a5170d0432cc3a644b36ffc50?s=128&d=identicon&r=PG&f=1",
                    "display_name": "swiftsly",
                    "link": "https://stackoverflow.com/users/2716435/swiftsly",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1586542644,
                "creation_date": 1586542644,
                "answer_id": 61146261,
                "question_id": 61143855,
            },
            {
                "owner": {
                    "reputation": 66,
                    "user_id": 420457,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/cf4d7bbda2e443f0fce904b32fbfb549?s=128&d=identicon&r=PG",
                    "display_name": "Anthony Leotta",
                    "link": "https://stackoverflow.com/users/420457/anthony-leotta",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1586542508,
                "last_edit_date": 1586542508,
                "creation_date": 1586534793,
                "answer_id": 61144113,
                "question_id": 60012421,
            },
            {
                "owner": {
                    "reputation": 7910,
                    "user_id": 1022260,
                    "user_type": "registered",
                    "accept_rate": 53,
                    "profile_image": "https://www.gravatar.com/avatar/27a141cb4a1a2f49d43bc09a5fa742b2?s=128&d=identicon&r=PG&f=1",
                    "display_name": "mikeb",
                    "link": "https://stackoverflow.com/users/1022260/mikeb",
                },
                "is_accepted": False,
                "score": 1,
                "last_activity_date": 1586541592,
                "creation_date": 1586541592,
                "answer_id": 61145978,
                "question_id": 61145838,
            },
            {
                "owner": {
                    "reputation": 1,
                    "user_id": 9241740,
                    "user_type": "registered",
                    "profile_image": "https://graph.facebook.com/2020653631295871/picture?type=large",
                    "display_name": "Anurag Trivedi",
                    "link": "https://stackoverflow.com/users/9241740/anurag-trivedi",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1586533579,
                "last_edit_date": 1586533579,
                "creation_date": 1586533155,
                "answer_id": 61143687,
                "question_id": 59795026,
            },
            {
                "owner": {
                    "reputation": 59,
                    "user_id": 11457625,
                    "user_type": "registered",
                    "profile_image": "https://lh6.googleusercontent.com/-snPAsLmGVqM/AAAAAAAAAAI/AAAAAAAAMFE/9MfA-QiX_Ns/photo.jpg?sz=128",
                    "display_name": "a zEnItH",
                    "link": "https://stackoverflow.com/users/11457625/a-zenith",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1586531086,
                "last_edit_date": 1586531086,
                "creation_date": 1586530323,
                "answer_id": 61142860,
                "question_id": 48607198,
            },
            {
                "owner": {
                    "reputation": 977,
                    "user_id": 11362370,
                    "user_type": "registered",
                    "profile_image": "https://lh3.googleusercontent.com/-0xjQIacCkX4/AAAAAAAAAAI/AAAAAAAAABA/suuL-MT8Ryk/photo.jpg?sz=128",
                    "display_name": "Abhishek Kulkarni",
                    "link": "https://stackoverflow.com/users/11362370/abhishek-kulkarni",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1586527184,
                "creation_date": 1586527184,
                "answer_id": 61141873,
                "question_id": 61141464,
            },
            {
                "owner": {
                    "reputation": 138,
                    "user_id": 9631728,
                    "user_type": "registered",
                    "profile_image": "https://i.stack.imgur.com/GKSkl.jpg?s=128&g=1",
                    "display_name": "Shirantha Madusanka",
                    "link": "https://stackoverflow.com/users/9631728/shirantha-madusanka",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1586522506,
                "creation_date": 1586522506,
                "answer_id": 61140473,
                "question_id": 44555184,
            },
            {
                "owner": {
                    "reputation": 977,
                    "user_id": 11362370,
                    "user_type": "registered",
                    "profile_image": "https://lh3.googleusercontent.com/-0xjQIacCkX4/AAAAAAAAAAI/AAAAAAAAABA/suuL-MT8Ryk/photo.jpg?sz=128",
                    "display_name": "Abhishek Kulkarni",
                    "link": "https://stackoverflow.com/users/11362370/abhishek-kulkarni",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1586515218,
                "creation_date": 1586515218,
                "answer_id": 61138554,
                "question_id": 61137457,
            },
            {
                "owner": {
                    "reputation": 482,
                    "user_id": 4285029,
                    "user_type": "registered",
                    "profile_image": "https://lh3.googleusercontent.com/-kInIHsdKyy4/AAAAAAAAAAI/AAAAAAAAAO0/rg5lnOEILaE/photo.jpg?sz=128",
                    "display_name": "Lambo",
                    "link": "https://stackoverflow.com/users/4285029/lambo",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1586514783,
                "last_edit_date": 1586514783,
                "creation_date": 1586419991,
                "answer_id": 61116700,
                "question_id": 61116006,
            },
            {
                "owner": {
                    "reputation": 55,
                    "user_id": 10798048,
                    "user_type": "registered",
                    "profile_image": "https://lh6.googleusercontent.com/-nd3DZD24xPo/AAAAAAAAAAI/AAAAAAAAB-8/1Ztgw8HoPUY/photo.jpg?sz=128",
                    "display_name": "Dhruv Agarwal",
                    "link": "https://stackoverflow.com/users/10798048/dhruv-agarwal",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1586486791,
                "creation_date": 1586486791,
                "answer_id": 61133285,
                "question_id": 61070409,
            },
            {
                "owner": {
                    "reputation": 446,
                    "user_id": 3888551,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/bbdd44ce930105bde69c0f04d6a8e402?s=128&d=identicon&r=PG&f=1",
                    "display_name": "merrydeath",
                    "link": "https://stackoverflow.com/users/3888551/merrydeath",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1580546747,
                "creation_date": 1580546747,
                "answer_id": 60015344,
                "question_id": 60012421,
            },
            {
                "owner": {
                    "reputation": 1994,
                    "user_id": 11714114,
                    "user_type": "registered",
                    "profile_image": "https://i.stack.imgur.com/qKzVA.jpg?s=128&g=1",
                    "display_name": "mario",
                    "link": "https://stackoverflow.com/users/11714114/mario",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1579530779,
                "creation_date": 1579530779,
                "answer_id": 59825413,
                "question_id": 59795026,
            },
            {
                "owner": {
                    "reputation": 134,
                    "user_id": 4696783,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/54af5b5ba107aa210e9c9f41c4cadae8?s=128&d=identicon&r=PG&f=1",
                    "display_name": "alessandrocaprarelli",
                    "link": "https://stackoverflow.com/users/4696783/alessandrocaprarelli",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1573999252,
                "creation_date": 1573999252,
                "answer_id": 58901221,
                "question_id": 56406960,
            },
            {
                "owner": {
                    "reputation": 1,
                    "user_id": 12213979,
                    "user_type": "registered",
                    "profile_image": "https://lh3.googleusercontent.com/a-/AAuE7mBio3jPxxKItIYXGKxPJhPz8s7Ov-UhofIhwA9L=k-s128",
                    "display_name": "Haoran Li",
                    "link": "https://stackoverflow.com/users/12213979/haoran-li",
                },
                "is_accepted": False,
                "score": 0,
                "last_activity_date": 1571051271,
                "creation_date": 1571051271,
                "answer_id": 58375513,
                "question_id": 56406960,
            },
            {
                "owner": {
                    "reputation": 11,
                    "user_id": 3081816,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/b337785224ff52cd46c86091cb0f8c94?s=128&d=identicon&r=PG",
                    "display_name": "Karloku",
                    "link": "https://stackoverflow.com/users/3081816/karloku",
                },
                "is_accepted": False,
                "score": 1,
                "last_activity_date": 1535363899,
                "last_edit_date": 1535363899,
                "creation_date": 1535362840,
                "answer_id": 52036526,
                "question_id": 42129181,
            },
            {
                "owner": {
                    "reputation": 173,
                    "user_id": 1544447,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/ba3dde1d65485c6bbb66329caf1b5788?s=128&d=identicon&r=PG",
                    "display_name": "Milan",
                    "link": "https://stackoverflow.com/users/1544447/milan",
                },
                "is_accepted": True,
                "score": 6,
                "last_activity_date": 1517752983,
                "last_edit_date": 1517752983,
                "creation_date": 1517742421,
                "answer_id": 48607411,
                "question_id": 48607198,
            },
            {
                "owner": {
                    "reputation": 91,
                    "user_id": 8162726,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/59efc4c64a9fb02364fa0b5920204374?s=128&d=identicon&r=PG&f=1",
                    "display_name": "dagda88",
                    "link": "https://stackoverflow.com/users/8162726/dagda88",
                },
                "is_accepted": False,
                "score": 1,
                "last_activity_date": 1497534487,
                "creation_date": 1497534487,
                "answer_id": 44569250,
                "question_id": 44555184,
            },
            {
                "owner": {
                    "reputation": 2243,
                    "user_id": 3866610,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/a86160be9ee19d4597efee7395f0f12a?s=128&d=identicon&r=PG",
                    "display_name": "Piotr Dawidiuk",
                    "link": "https://stackoverflow.com/users/3866610/piotr-dawidiuk",
                },
                "is_accepted": False,
                "score": 4,
                "last_activity_date": 1486660784,
                "creation_date": 1486660784,
                "answer_id": 42142986,
                "question_id": 42129181,
            },
            {
                "owner": {
                    "reputation": 1325,
                    "user_id": 1589921,
                    "user_type": "registered",
                    "accept_rate": 100,
                    "profile_image": "https://www.gravatar.com/avatar/6689a7708fc36362b733946d1cceb2e2?s=128&d=identicon&r=PG",
                    "display_name": "sjudǝʊ",
                    "link": "https://stackoverflow.com/users/1589921/sjud%c7%9d%ca%8a",
                },
                "is_accepted": False,
                "score": 7,
                "last_activity_date": 1456920847,
                "creation_date": 1456920847,
                "answer_id": 35746942,
                "question_id": 35736499,
            },
        ],
        "has_more": False,
        "quota_max": 10000,
        "quota_remaining": 9967,
    }


@pytest.fixture
def svf_search_result():
    return {
        "items": [
            {
                "tags": ["post", "flask", "get", "insomnia"],
                "owner": {
                    "reputation": 1,
                    "user_id": 13277169,
                    "user_type": "registered",
                    "profile_image": "https://lh5.googleusercontent.com/-yqVOsch0cTo/AAAAAAAAAAI/AAAAAAAAAAA/AAKWJJPV7XyWhxOtCU-oKujHRPEscv-Tbg/photo.jpg?sz=128",
                    "display_name": "Carlos Amorim",
                    "link": "https://stackoverflow.com/users/13277169/carlos-amorim",
                },
                "is_answered": False,
                "view_count": 14,
                "answer_count": 1,
                "score": 0,
                "last_activity_date": 1586548352,
                "creation_date": 1586510923,
                "last_edit_date": 1586514754,
                "question_id": 61137457,
                "link": "https://stackoverflow.com/questions/61137457/get-and-post-data-in-flask-request",
                "title": "Get and Post data in Flask request",
            },
            {
                "tags": ["python", "rest", "cookies", "backend", "endpoint"],
                "owner": {
                    "reputation": 41,
                    "user_id": 6254919,
                    "user_type": "registered",
                    "profile_image": "https://i.stack.imgur.com/g99ct.jpg?s=128&g=1",
                    "display_name": "max goh",
                    "link": "https://stackoverflow.com/users/6254919/max-goh",
                },
                "is_answered": True,
                "view_count": 2384,
                "answer_count": 3,
                "score": 3,
                "last_activity_date": 1586547778,
                "creation_date": 1486619389,
                "last_edit_date": 1486627145,
                "question_id": 42129181,
                "link": "https://stackoverflow.com/questions/42129181/flask-restful-creating-a-cookie-from-an-endpoint-restful-resource",
                "title": "Flask RESTFUL, creating a cookie from an endpoint (restful.Resource)",
            },
            {
                "tags": ["python-2.7", "opencv", "flask", "face-recognition"],
                "owner": {
                    "reputation": 51,
                    "user_id": 5548582,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/40f99b65b35e37c0404820add0fa904b?s=128&d=identicon&r=PG&f=1",
                    "display_name": "Chip",
                    "link": "https://stackoverflow.com/users/5548582/chip",
                },
                "is_answered": True,
                "view_count": 3524,
                "answer_count": 2,
                "score": 3,
                "last_activity_date": 1586547410,
                "creation_date": 1456879859,
                "question_id": 35736499,
                "link": "https://stackoverflow.com/questions/35736499/access-clients-webcam-from-flask-server",
                "title": "Access clients webcam from Flask server",
            },
            {
                "tags": [
                    "python-3.x",
                    "flask-sqlalchemy",
                    "flask-marshmallow",
                    "marshmallow-sqlalchemy",
                ],
                "owner": {
                    "reputation": 13998,
                    "user_id": 313389,
                    "user_type": "registered",
                    "accept_rate": 60,
                    "profile_image": "https://www.gravatar.com/avatar/90542ab4ef51518d0fc4f1d7a7f7e78d?s=128&d=identicon&r=PG",
                    "display_name": "hd.",
                    "link": "https://stackoverflow.com/users/313389/hd",
                },
                "is_answered": False,
                "view_count": 27,
                "answer_count": 1,
                "score": 0,
                "last_activity_date": 1586547349,
                "creation_date": 1574077358,
                "question_id": 58913803,
                "link": "https://stackoverflow.com/questions/58913803/what-is-replacement-of-fields-method-in-flask-marshmallow",
                "title": "What is replacement of fields.Method in flask-marshmallow?",
            },
            {
                "tags": ["python", "flask", "jinja2"],
                "owner": {
                    "reputation": 21,
                    "user_id": 9579690,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/eb8f511fdc7b5626469e22c4ee9cba2f?s=128&d=identicon&r=PG&f=1",
                    "display_name": "A.Ranjan",
                    "link": "https://stackoverflow.com/users/9579690/a-ranjan",
                },
                "is_answered": False,
                "view_count": 30,
                "answer_count": 1,
                "score": 0,
                "last_activity_date": 1586547288,
                "creation_date": 1586489943,
                "question_id": 61133669,
                "link": "https://stackoverflow.com/questions/61133669/i-need-to-dispaly-2-for-loop-data-in-2-seperate-column-using-jinja-flask",
                "title": "I need to dispaly 2 for loop data in 2 seperate column using jinja (flask)",
            },
            {
                "tags": ["python", "pandas", "flask", "routes"],
                "owner": {
                    "reputation": 1,
                    "user_id": 6575393,
                    "user_type": "registered",
                    "profile_image": "https://graph.facebook.com/1118236321556088/picture?type=large",
                    "display_name": "Joel Klein",
                    "link": "https://stackoverflow.com/users/6575393/joel-klein",
                },
                "is_answered": False,
                "view_count": 61,
                "answer_count": 0,
                "score": 0,
                "last_activity_date": 1586546665,
                "creation_date": 1580155516,
                "last_edit_date": 1586546665,
                "question_id": 59938156,
                "link": "https://stackoverflow.com/questions/59938156/flask-use-file-in-multiple-routes",
                "title": "Flask: Use File in multiple routes",
            },
            {
                "tags": ["python", "mysql", "flask", "flask-mysql"],
                "owner": {
                    "reputation": 73,
                    "user_id": 12742438,
                    "user_type": "registered",
                    "profile_image": "https://lh3.googleusercontent.com/-3Fle6rtploA/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rdFnvMsqr6fkShUZUCweNn5CMGgoQ/photo.jpg?sz=128",
                    "display_name": "redbulll",
                    "link": "https://stackoverflow.com/users/12742438/redbulll",
                },
                "is_answered": True,
                "view_count": 17,
                "accepted_answer_id": 61146580,
                "answer_count": 1,
                "score": 0,
                "last_activity_date": 1586543887,
                "creation_date": 1586542630,
                "last_edit_date": 1586543887,
                "question_id": 61146256,
                "link": "https://stackoverflow.com/questions/61146256/installing-flask-mysqldb-gives-mysql-config-not-found",
                "title": "Installing flask-mysqldb gives &quot;mysql_config not found&quot;",
            },
            {
                "tags": ["docker", "nginx", "flask", "reverse-proxy", "gunicorn"],
                "owner": {
                    "reputation": 63,
                    "user_id": 10994626,
                    "user_type": "registered",
                    "profile_image": "https://i.stack.imgur.com/KjqaP.png?s=128&g=1",
                    "display_name": "norsemanGrey",
                    "link": "https://stackoverflow.com/users/10994626/norsemangrey",
                },
                "is_answered": False,
                "view_count": 4,
                "answer_count": 0,
                "score": 0,
                "last_activity_date": 1586543848,
                "creation_date": 1586543848,
                "question_id": 61146588,
                "link": "https://stackoverflow.com/questions/61146588/nginx-properties-for-reverse-proxy-of-flask-app-w-gunicorn-on-docker",
                "title": "Nginx Properties for Reverse Proxy of Flask App w/Gunicorn on Docker",
            },
            {
                "tags": ["python", "flask", "ldap", "openldap", "flask-login"],
                "owner": {
                    "reputation": 683,
                    "user_id": 2716435,
                    "user_type": "registered",
                    "accept_rate": 65,
                    "profile_image": "https://www.gravatar.com/avatar/779bb55a5170d0432cc3a644b36ffc50?s=128&d=identicon&r=PG&f=1",
                    "display_name": "swiftsly",
                    "link": "https://stackoverflow.com/users/2716435/swiftsly",
                },
                "is_answered": False,
                "view_count": 11,
                "answer_count": 1,
                "score": 1,
                "last_activity_date": 1586542644,
                "creation_date": 1586533837,
                "question_id": 61143855,
                "link": "https://stackoverflow.com/questions/61143855/ldapinvaliddnsyntaxresult-error-when-binding-ldap-connection-in-flask-app",
                "title": "LDAPInvalidDNSyntaxResult error when binding LDAP connection in Flask app",
            },
            {
                "tags": ["python", "flask", "error-handling", "python-import"],
                "owner": {
                    "reputation": 1,
                    "user_id": 6342258,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/780b8e31fa9606bceb76960d7f5b1fee?s=128&d=identicon&r=PG&f=1",
                    "display_name": "Arrchana",
                    "link": "https://stackoverflow.com/users/6342258/arrchana",
                },
                "is_answered": False,
                "view_count": 90,
                "answer_count": 2,
                "score": 0,
                "last_activity_date": 1586542508,
                "creation_date": 1580511717,
                "last_edit_date": 1580602046,
                "question_id": 60012421,
                "link": "https://stackoverflow.com/questions/60012421/flask-modulenotfounderror-when-use-flask-run-but-able-to-run-app-using-pytho",
                "title": "Flask: ModuleNotFoundError when use `flask run` but able to run app using `python app.py`",
            },
            {
                "tags": ["nginx", "flask", "ubuntu-18.04", "uwsgi", "pyodbc"],
                "owner": {
                    "reputation": 1,
                    "user_id": 10329112,
                    "user_type": "registered",
                    "profile_image": "https://lh4.googleusercontent.com/-2g4K50HAMIo/AAAAAAAAAAI/AAAAAAAAAHM/N7FTnJEscJw/photo.jpg?sz=128",
                    "display_name": "Naren Vema",
                    "link": "https://stackoverflow.com/users/10329112/naren-vema",
                },
                "is_answered": False,
                "view_count": 5,
                "answer_count": 0,
                "score": 0,
                "last_activity_date": 1586541686,
                "creation_date": 1586541686,
                "question_id": 61146009,
                "link": "https://stackoverflow.com/questions/61146009/flask-application-running-on-uwsgi-and-nginx-crashes-with-sql-server-transaction",
                "title": "Flask application running on uwsgi and nginx crashes with SQL Server transaction error",
            },
            {
                "tags": ["python", "flask"],
                "owner": {
                    "reputation": 23,
                    "user_id": 11550323,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/fb8d082e652f794c8ff589ae68619d0f?s=128&d=identicon&r=PG&f=1",
                    "display_name": "simonsays",
                    "link": "https://stackoverflow.com/users/11550323/simonsays",
                },
                "is_answered": True,
                "view_count": 15,
                "accepted_answer_id": 61145970,
                "answer_count": 2,
                "score": 0,
                "last_activity_date": 1586541592,
                "creation_date": 1586541124,
                "last_edit_date": 1586541565,
                "question_id": 61145838,
                "link": "https://stackoverflow.com/questions/61145838/flask-using-outputs-from-a-function-inside-another-function",
                "title": "Flask - using outputs from a function inside another Function",
            },
            {
                "tags": ["python", "linux", "flask", "server"],
                "owner": {
                    "reputation": 19,
                    "user_id": 3857851,
                    "user_type": "registered",
                    "profile_image": "https://graph.facebook.com/542270227/picture?type=large",
                    "display_name": "Jlearner",
                    "link": "https://stackoverflow.com/users/3857851/jlearner",
                },
                "is_answered": False,
                "view_count": 6,
                "answer_count": 0,
                "score": -1,
                "last_activity_date": 1586541289,
                "creation_date": 1586541289,
                "question_id": 61145884,
                "link": "https://stackoverflow.com/questions/61145884/siteground-hosting-python-flask-server",
                "title": "Siteground - hosting python flask server",
            },
            {
                "tags": ["python", "sqlalchemy", "marshmallow"],
                "owner": {
                    "reputation": 1663,
                    "user_id": 4729764,
                    "user_type": "registered",
                    "accept_rate": 68,
                    "profile_image": "https://www.gravatar.com/avatar/aa45447daa10fb1175ae9f3261edd01b?s=128&d=identicon&r=PG",
                    "display_name": "GRS",
                    "link": "https://stackoverflow.com/users/4729764/grs",
                },
                "is_answered": False,
                "view_count": 8,
                "answer_count": 0,
                "score": 0,
                "last_activity_date": 1586539127,
                "creation_date": 1586539127,
                "question_id": 61145322,
                "link": "https://stackoverflow.com/questions/61145322/api-design-using-flask-combining-sql-alchemy-and-marshmallow",
                "title": "API design using Flask, combining SQL Alchemy and Marshmallow",
            },
            {
                "tags": ["python", "flask", "cookies", "jwt"],
                "owner": {
                    "reputation": 4312,
                    "user_id": 3451339,
                    "user_type": "registered",
                    "accept_rate": 87,
                    "profile_image": "https://i.stack.imgur.com/HPuzK.png?s=128&g=1",
                    "display_name": "8-Bit Borges",
                    "link": "https://stackoverflow.com/users/3451339/8-bit-borges",
                },
                "is_answered": False,
                "view_count": 54,
                "bounty_amount": 50,
                "bounty_closes_date": 1587089663,
                "answer_count": 1,
                "score": 0,
                "last_activity_date": 1586536399,
                "creation_date": 1586214987,
                "last_edit_date": 1586536399,
                "question_id": 61070409,
                "link": "https://stackoverflow.com/questions/61070409/flask-unable-to-get-cookies",
                "title": "Flask - unable to get cookies",
            },
            {
                "tags": ["python", "flask", "flask-wtforms"],
                "owner": {
                    "reputation": 513,
                    "user_id": 9776699,
                    "user_type": "registered",
                    "profile_image": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=128",
                    "display_name": "Kevin Nash",
                    "link": "https://stackoverflow.com/users/9776699/kevin-nash",
                },
                "is_answered": False,
                "view_count": 15,
                "answer_count": 0,
                "score": 0,
                "last_activity_date": 1586534932,
                "creation_date": 1586534932,
                "question_id": 61144150,
                "link": "https://stackoverflow.com/questions/61144150/flask-returning-values-of-fields-that-were-selected",
                "title": "Flask - Returning values of fields that were selected",
            },
            {
                "tags": ["python", "docker", "flask", "kubernetes", "minikube"],
                "owner": {
                    "reputation": 1,
                    "user_id": 12191706,
                    "user_type": "registered",
                    "profile_image": "https://lh3.googleusercontent.com/a-/AAuE7mD0TK4RpZDfizQOjb02GOLQPADHUkjdfI0gGAhYlg=k-s128",
                    "display_name": "Arturo Avil&#233;s",
                    "link": "https://stackoverflow.com/users/12191706/arturo-avil%c3%a9s",
                },
                "is_answered": False,
                "view_count": 70,
                "answer_count": 2,
                "score": 0,
                "last_activity_date": 1586533579,
                "creation_date": 1579296277,
                "question_id": 59795026,
                "link": "https://stackoverflow.com/questions/59795026/how-to-make-a-request-from-a-flask-api-in-a-kubernetes-namespace-to-another-flas",
                "title": "How to make a request from a Flask API in a Kubernetes Namespace to another Flask API in another namespace internally (Using the DNS) using minikube",
            },
            {
                "tags": ["python", "google-app-engine", "flask"],
                "owner": {
                    "reputation": 3,
                    "user_id": 7819769,
                    "user_type": "registered",
                    "accept_rate": 50,
                    "profile_image": "https://i.stack.imgur.com/pgBax.jpg?s=128&g=1",
                    "display_name": "akbharath",
                    "link": "https://stackoverflow.com/users/7819769/akbharath",
                },
                "is_answered": False,
                "view_count": 23,
                "answer_count": 0,
                "score": 0,
                "last_activity_date": 1586531316,
                "creation_date": 1586526706,
                "last_edit_date": 1586531316,
                "question_id": 61141716,
                "link": "https://stackoverflow.com/questions/61141716/trying-to-deploy-a-python-web-app-with-flask-to-gae",
                "title": "Trying to deploy a python web app with flask to GAE",
            },
            {
                "tags": ["python", "postman", "flask-restful"],
                "owner": {
                    "reputation": 33,
                    "user_id": 9243416,
                    "user_type": "registered",
                    "profile_image": "https://graph.facebook.com/1566750923439234/picture?type=large",
                    "display_name": "VPJ",
                    "link": "https://stackoverflow.com/users/9243416/vpj",
                },
                "is_answered": True,
                "view_count": 3713,
                "accepted_answer_id": 48607411,
                "answer_count": 2,
                "score": 2,
                "last_activity_date": 1586531086,
                "creation_date": 1517740869,
                "last_edit_date": 1517749052,
                "question_id": 48607198,
                "link": "https://stackoverflow.com/questions/48607198/how-to-send-an-image-to-a-flask-server-using-postman",
                "title": "How to send an image to a flask server using Postman",
            },
            {
                "tags": ["python", "mongodb", "flask"],
                "owner": {
                    "reputation": 21,
                    "user_id": 11923283,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/95956e29eb4dc594c0917b9762cffe46?s=128&d=identicon&r=PG&f=1",
                    "display_name": "Brendan O&#39;Shea",
                    "link": "https://stackoverflow.com/users/11923283/brendan-oshea",
                },
                "is_answered": False,
                "view_count": 13,
                "answer_count": 0,
                "score": -1,
                "last_activity_date": 1586530906,
                "creation_date": 1586530906,
                "question_id": 61143056,
                "link": "https://stackoverflow.com/questions/61143056/flask-redirect-after-post-going-to-wrong-place",
                "title": "flask redirect after post going to wrong place",
            },
            {
                "tags": ["python", "jquery", "flask"],
                "owner": {
                    "reputation": 309,
                    "user_id": 4906481,
                    "user_type": "registered",
                    "accept_rate": 75,
                    "profile_image": "https://www.gravatar.com/avatar/10ea6265b5597159213715d0e6720886?s=128&d=identicon&r=PG",
                    "display_name": "Vasu Mistry",
                    "link": "https://stackoverflow.com/users/4906481/vasu-mistry",
                },
                "is_answered": False,
                "view_count": 11,
                "answer_count": 0,
                "score": 0,
                "last_activity_date": 1586530440,
                "creation_date": 1586530440,
                "question_id": 61142901,
                "link": "https://stackoverflow.com/questions/61142901/oauth-with-flask-jquery-how-do-i-capture-redirect-url-from-flask-response-obje",
                "title": "OAuth with Flask, Jquery: How do I capture redirect url from flask response object at frontend",
            },
            {
                "tags": ["python", "html", "flask"],
                "owner": {
                    "reputation": 45,
                    "user_id": 11901150,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/463afb922824fd6d9553ad174050a54f?s=128&d=identicon&r=PG&f=1",
                    "display_name": "PiedBouche",
                    "link": "https://stackoverflow.com/users/11901150/piedbouche",
                },
                "is_answered": False,
                "view_count": 76,
                "answer_count": 0,
                "score": 0,
                "last_activity_date": 1586529106,
                "creation_date": 1565948000,
                "last_edit_date": 1586529106,
                "question_id": 57522218,
                "link": "https://stackoverflow.com/questions/57522218/display-multiple-images-with-flask",
                "title": "Display multiple images with Flask",
            },
            {
                "tags": ["javascript", "python", "json", "flask", "jinja2"],
                "owner": {
                    "reputation": 35,
                    "user_id": 12191649,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/e7c14a29127065f1482380db33360737?s=128&d=identicon&r=PG&f=1",
                    "display_name": "Mar",
                    "link": "https://stackoverflow.com/users/12191649/mar",
                },
                "is_answered": False,
                "view_count": 16,
                "answer_count": 1,
                "score": 0,
                "last_activity_date": 1586527184,
                "creation_date": 1586525811,
                "question_id": 61141464,
                "link": "https://stackoverflow.com/questions/61141464/how-to-read-json-list-in-flask-template",
                "title": "How to read json list in flask template",
            },
            {
                "tags": ["flask", "heroku", "flask-admin"],
                "owner": {
                    "reputation": 1461,
                    "user_id": 1298483,
                    "user_type": "registered",
                    "accept_rate": 41,
                    "profile_image": "https://www.gravatar.com/avatar/3aaea9965fe8d8be5d032dcfbf50c5e1?s=128&d=identicon&r=PG",
                    "display_name": "RailsTweeter",
                    "link": "https://stackoverflow.com/users/1298483/railstweeter",
                },
                "is_answered": False,
                "view_count": 7,
                "answer_count": 0,
                "score": 0,
                "last_activity_date": 1586526618,
                "creation_date": 1586526618,
                "question_id": 61141690,
                "link": "https://stackoverflow.com/questions/61141690/options-set-in-flask-admin-cached-by-app-how-to-flush-cache",
                "title": "Options set in Flask Admin, cached by app, how to flush cache?",
            },
            {
                "tags": ["python", "flask", "http-post", "werkzeug"],
                "owner": {
                    "reputation": 91,
                    "user_id": 8162726,
                    "user_type": "registered",
                    "profile_image": "https://www.gravatar.com/avatar/59efc4c64a9fb02364fa0b5920204374?s=128&d=identicon&r=PG&f=1",
                    "display_name": "dagda88",
                    "link": "https://stackoverflow.com/users/8162726/dagda88",
                },
                "is_answered": True,
                "view_count": 597,
                "answer_count": 2,
                "score": 4,
                "last_activity_date": 1586522506,
                "creation_date": 1497476472,
                "question_id": 44555184,
                "link": "https://stackoverflow.com/questions/44555184/in-a-connexion-flask-app-how-can-i-fake-post-requests-with-parameters-in-body-f",
                "title": "In a connexion/flask app, how can I fake post requests with parameters in body for endpoint?",
            },
            {
                "tags": ["python", "html", "forms", "validation", "flask"],
                "owner": {
                    "reputation": 29,
                    "user_id": 13183329,
                    "user_type": "registered",
                    "profile_image": "https://lh6.googleusercontent.com/-SaPAdIikZc0/AAAAAAAAAAI/AAAAAAAAAAA/AAKWJJPLrJMpkxVqAykxVKhavUB4RT_uig/photo.jpg?sz=128",
                    "display_name": "moro_922",
                    "link": "https://stackoverflow.com/users/13183329/moro-922",
                },
                "is_answered": False,
                "view_count": 9,
                "answer_count": 0,
                "score": 0,
                "last_activity_date": 1586519507,
                "creation_date": 1586519507,
                "question_id": 61139683,
                "link": "https://stackoverflow.com/questions/61139683/how-to-show-an-error-or-confirmation-form-in-flask-based-on-python-code",
                "title": "How to show an error or confirmation form in Flask based on PYTHON code?",
            },
            {
                "tags": ["python", "google-app-engine", "flask", "latency"],
                "owner": {
                    "reputation": 83,
                    "user_id": 1209986,
                    "user_type": "registered",
                    "accept_rate": 0,
                    "profile_image": "https://www.gravatar.com/avatar/6504005259d2af22c6802e4ced59d895?s=128&d=identicon&r=PG",
                    "display_name": "Yanone",
                    "link": "https://stackoverflow.com/users/1209986/yanone",
                },
                "is_answered": False,
                "view_count": 12,
                "answer_count": 0,
                "score": 0,
                "last_activity_date": 1586518115,
                "creation_date": 1586518115,
                "question_id": 61139339,
                "link": "https://stackoverflow.com/questions/61139339/google-app-engine-standard-env-w-python-3-flask-high-latency-for-non-post",
                "title": "Google App Engine Standard Env w/ Python 3 &amp; Flask: High latency for (non-)POST requests",
            },
            {
                "tags": ["flask", "deployment", "centos"],
                "owner": {
                    "reputation": 1,
                    "user_id": 6448606,
                    "user_type": "registered",
                    "profile_image": "https://graph.facebook.com/715391861933227/picture?type=large",
                    "display_name": "Divyanshi Singhal",
                    "link": "https://stackoverflow.com/users/6448606/divyanshi-singhal",
                },
                "is_answered": False,
                "view_count": 10,
                "answer_count": 0,
                "score": 0,
                "last_activity_date": 1586516952,
                "creation_date": 1586516952,
                "question_id": 61139049,
                "link": "https://stackoverflow.com/questions/61139049/how-to-deploy-flask-on-centos-server",
                "title": "how to deploy flask on centos server?",
            },
            {
                "tags": ["python", "flask", "docsify"],
                "owner": {
                    "reputation": 310,
                    "user_id": 5179129,
                    "user_type": "registered",
                    "accept_rate": 83,
                    "profile_image": "https://i.stack.imgur.com/LlVFn.png?s=128&g=1",
                    "display_name": "RancheroBeans",
                    "link": "https://stackoverflow.com/users/5179129/rancherobeans",
                },
                "is_answered": False,
                "view_count": 261,
                "answer_count": 2,
                "score": 1,
                "last_activity_date": 1586516219,
                "creation_date": 1559393777,
                "question_id": 56406960,
                "link": "https://stackoverflow.com/questions/56406960/basic-flask-implementation-of-docsify-documentation",
                "title": "Basic flask implementation of Docsify documentation",
            },
            {
                "tags": [
                    "python",
                    "flask",
                    "sqlalchemy",
                    "flask-sqlalchemy",
                    "flask-jwt-extended",
                ],
                "owner": {
                    "reputation": 31,
                    "user_id": 8247009,
                    "user_type": "registered",
                    "profile_image": "https://graph.facebook.com/1214875081991957/picture?type=large",
                    "display_name": "Mahmoud Zougheb",
                    "link": "https://stackoverflow.com/users/8247009/mahmoud-zougheb",
                },
                "is_answered": False,
                "view_count": 18,
                "answer_count": 1,
                "score": 1,
                "last_activity_date": 1586514783,
                "creation_date": 1586417272,
                "last_edit_date": 1586425389,
                "question_id": 61116006,
                "link": "https://stackoverflow.com/questions/61116006/how-can-i-get-the-current-userid-in-flask-jwt-extended",
                "title": "How can I get the current user(id) in flask-jwt-extended?",
            },
        ],
        "has_more": True,
        "quota_max": 10000,
        "quota_remaining": 9991,
    }


@pytest.fixture
def mocked_api(svf_search_result, svf_answers_result):
    with respx.mock(base_url=StackOverflow.url()) as httpx_mock:
        httpx_mock.get(
            "/search?site=stackoverflow&intitle=flask",
            content=svf_search_result,
            alias="questions",
        )
        questions_ids = list(
            map(str, StackOverflow.extract_question_ids(svf_search_result))
        )
        httpx_mock.get(
            f"/questions/{';'.join(questions_ids)}/answers",
            content=svf_answers_result,
            alias="answers",
        )
        yield httpx_mock
